import type { DB } from './types'

/**
 * Datos iniciales. Los precios son tentativos (ARS), tomados de rangos publicados
 * para lavado a domicilio en Argentina (abril 2026). Todo se edita desde el panel de administración.
 */
export const seed: DB = {
  settings: {
    businessName: 'Brillo Móvil',
    tagline: 'Tu auto limpio mientras disfrutás tu día',
    primaryColor: '#0e7490',
    whatsapp: '',
    adminPin: '1234',
    cancelHours: 12,
    bookingHorizonDays: 28,
    minAdvanceHours: 12,
    payMethods: { mp: true, transfer: true, cash: true },
    mpLink: '',
    transferAlias: '',
    transferCbu: '',
    transferHolder: '',
    cashNote: 'Podés pagar en efectivo en el momento del servicio.',
    promoText: 'Primer lavado con 10% de descuento consultando por WhatsApp.',
    waTemplate: 'Hola {nombre}, te escribimos de Brillo Móvil por tu turno de {servicio} el {fecha} a las {hora} en {barrio}.',
    terms:
      'Si llueve reprogramamos sin cargo. Cancelaciones sin costo hasta el plazo indicado; pasado ese plazo puede cobrarse el turno.',
  },
  services: [
    { id: 'ext', name: 'Lavado exterior', description: 'Carrocería, llantas, vidrios y secado.', minutes: 30, active: true },
    { id: 'int', name: 'Lavado interior', description: 'Aspirado, tablero, paneles y vidrios interiores.', minutes: 40, active: true },
    { id: 'full', name: 'Lavado completo', description: 'Exterior + interior. El más elegido.', minutes: 60, active: true },
    { id: 'prem', name: 'Premium', description: 'Completo + cera protectora y tratamiento de gomas y plásticos.', minutes: 90, active: true },
  ],
  categories: [
    { id: 'small', name: 'Auto chico / mediano', active: true },
    { id: 'suv', name: 'SUV / Pick-up', active: true },
  ],
  extras: [
    { id: 'perfume', name: 'Perfume', price: 2000, active: true },
    { id: 'pets', name: 'Pelos de mascota', price: 6000, active: true },
    { id: 'trunk', name: 'Limpieza de baúl', price: 4000, active: true },
    { id: 'engine', name: 'Lavado de motor', price: 12000, active: true },
  ],
  prices: {
    'ext:small': 13000,
    'ext:suv': 19500,
    'int:small': 16500,
    'int:suv': 24500,
    'full:small': 24500,
    'full:suv': 37000,
    'prem:small': 35000,
    'prem:suv': 50000,
  },
  sites: [
    {
      id: 'site-circulo',
      name: 'Club Círculo (Canning)',
      zone: 'Sur',
      mode: 'fixed',
      spotNote: 'Playa de estacionamiento del club, sector a confirmar con la administración.',
      days: [2],
      start: '09:00',
      end: '17:00',
      slotMinutes: 60,
      perSlot: 2,
      active: true,
      commissionType: 'none',
      commissionValue: 0,
      sitePin: '',
      clientNotice: '',
      siteNotice: '',
    },
    {
      id: 'site-escobar',
      name: 'Barrio cerrado en Escobar',
      zone: 'Norte',
      mode: 'home',
      spotNote: 'Se lava en la cochera o frente de la casa del cliente.',
      days: [4],
      start: '09:00',
      end: '17:00',
      slotMinutes: 60,
      perSlot: 2,
      active: true,
      commissionType: 'none',
      commissionValue: 0,
      sitePin: '',
      clientNotice: '',
      siteNotice: '',
    },
    {
      id: 'site-sanvicente',
      name: 'Barrio cerrado en San Vicente',
      zone: 'Sur',
      mode: 'fixed',
      spotNote: 'Lugar fijo dentro del barrio, a confirmar con la administración.',
      days: [5],
      start: '09:00',
      end: '17:00',
      slotMinutes: 60,
      perSlot: 2,
      active: true,
      commissionType: 'none',
      commissionValue: 0,
      sitePin: '',
      clientNotice: '',
      siteNotice: '',
    },
  ],
  closedDates: [],
  bookings: [],
}
